### ISSUE TITLE
API instead of internal wallet?

### ISSUE THREAD

**Issue by losh11** [deginner/lamassu-poloniex#1]
Is it really a good idea to use the Poloniex API instead of an internal client? I understand that using Dashd isn't good because of its need to download the entire blockchain, but why not use the parse command to remove all old txs, and when SegWit is implemented, the size of the blockchain will be further decreased.

Or if that's not possible, why doesn't this plugin just use the bitcoinjs equivalent for DASH, especially since it's a SVP wallet.

Using exchanges for holding DASH is a bad idea, and usually not recommended due to security issues. Exchanges are also not very reliable for sending txs out quickly... In the future, DASH may be available on other popular exchanges, so why is this being limited to Poloniex only? The day Poloniex goes down, so will this...

**Comment by g-p-g** [comment]
An exchange has to be used for the trading part, for balancing purchases. The other part, the wallet, can indeed use a different method, like the standard rpc. There are plugins using rpc and you should be able to use it nearly as is for Dash, and then it would be a matter of changing the Lamassu config to use that for the wallet plugin.

So, yes, it's possible to use a different plugin as the wallet. This is not limiting it to Poloniex, things can change.

**Comment by g-p-g** [comment]
I'm closing this as it is not to be the proper medium to discuss such things. Thanks for your input, it's being considered.

**Comment by losh11** [comment]
Do you have an email address that I can use to contact you guys?

**Comment by isysd** [comment]
@losh11 rather than publish an email address here, I created a gitter room for chatting about these topics. If you want to email us additionally, please use the contact form on http://deginner.com/contact/

https://gitter.im/deginner/dash-lamassu
